services:
  areweopen:
    image: ghcr.io/alexveebee/areweopen:latest
    restart: unless-stopped
    ports:
      - "8080:3000"
    volumes:
      - ./config:/app/config
    environment:
      - TZ=Europe/London