name: Build and Push

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    REPO_USER: alexveebee
    REPO_NAME: ${{ github.repository }}
    IMAGE_NAME: areweopen

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v2
   
        - name: Build and Push Docker image
          run: |
              docker buildx build --file dockerfile --iidfile /tmp/docker-build-push-1deP5g/iidfile --tag ghcr.io/alexveebee/areweopen/areweopen:latest --metadata-file /tmp/docker-build-push-1deP5g/metadata-file --push .
        
        # - name: build and push
        #   uses: docker/build-push-action@v2
        #   with:
        #         context: .
        #         file: dockerfile
        #         tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
        #         push: true
