on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    REPO_USER: ${{ github.actor }}
    REPO_NAME: ${{ github.repository }}
    IMAGE_NAME: areweopen

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v2
    
        - name: build and push
          uses: docker/build-push-action@v2
          with:
                context: .
                file: .dockerfile
                tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
                push: true
